### ISSUE TITLE
Quiet long operation

### ISSUE THREAD

**Issue by sebastienserre** [level-level/wp-cli-facetwp#2]
Hello,
I'm using your tool but it takes 24h and allways running to index 23845 posts & 137411 postmeta.
Is it normal ?
May I continue or someting broke ?

**Comment by NielsdeBlaauw** [comment]
Hi @sebastienserre,

Not sure if you still need this, but for others having similar issues: It's unlikely it should take so long, and output nothing at all. It should at least show some progress.
