### ISSUE TITLE
Better output

### ISSUE THREAD

**Issue by Drivingralle** [level-level/wp-cli-facetwp#3]
I just installed the plugin and started the re-indexing. Works great.

My problem with the output is that it doesn't tell my what it is doing.

What does it index: a post? a post-type?
Indexing  100% [===============================================] 1:45 / 1:35
Indexing  100% [===============================================] 1:33 / 3:16
Indexing  100% [===============================================] 1:20 / 4:42
Indexing  100% [===============================================] 1:29 / 5:21
Indexing  100% [=============================================] 1:50  / 11:16
Indexing  100% [===============================================] 1:54 / 9:23
Indexing  100% [===============================================] 1:35 / 9:28
Indexing  100% [=============================================] 2:00  / 13:08
Indexing  100% [=============================================] 1:53  / 13:16
Indexing  100% [=============================================] 1:45  / 17:19

From reading the plugin php file I guess the output shows one line per post. 

-----

I would love to see the post ID included in the output. 
Maybe even a count of how many posts have been and will be indexed.

**Comment by NielsdeBlaauw** [comment]
Hi @Drivingralle, 

Thanks for using the tool and providing feedback.
At the moment each progress bar represents 100 posts. 

We will think of a way to improve the output here to make clear what is happening during the process

**Comment by opicron** [comment]
See issue https://github.com/level-level/facetwp-wp-cli/issues/5 for an solution.

**Comment by NielsdeBlaauw** [comment]
Fixed in #7.
